version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: psi-server
    ports:
      - "1234:1234"
    networks:
      - psi-net
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  client:
    build:
      context: ./client
    container_name: psi-client
    command: python3 client.py server 1234
    depends_on:
      - server
    networks:
      - psi-net
    tty: true
    stdin_open: true

networks:
  psi-net:
    driver: bridge
